//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
  private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
      this.http = http ? http : window as any;
      this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:8080";
  }

  /**
   * @return OK
   */
  addNewUser(body: RegisterRequest): Promise<User> {
      let url_ = this.baseUrl + "/user/register";
      url_ = url_.replace(/[?&]$/, "");

      const content_ = JSON.stringify(body);

      let options_: RequestInit = {
          body: content_,
          method: "POST",
          headers: {
              "Content-Type": "application/json",
              "Accept": "*/*"
          }
      };

      return this.http.fetch(url_, options_).then((_response: Response) => {
          return this.processAddNewUser(_response);
      });
  }

  protected processAddNewUser(response: Response): Promise<User> {
      const status = response.status;
      let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
      if (status === 200) {
          return response.text().then((_responseText) => {
          let result200: any = null;
          let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = User.fromJS(resultData200);
          return result200;
          });
      } else if (status !== 200 && status !== 204) {
          return response.text().then((_responseText) => {
          return throwException("An unexpected server error occurred.", status, _responseText, _headers);
          });
      }
      return Promise.resolve<User>(null as any);
  }
}

export class RegisterRequest implements IRegisterRequest {
  email?: string;
  password?: string;

  [key: string]: any;

  constructor(data?: IRegisterRequest) {
      if (data) {
          for (var property in data) {
              if (data.hasOwnProperty(property))
                  (<any>this)[property] = (<any>data)[property];
          }
      }
  }

  init(_data?: any) {
      if (_data) {
          for (var property in _data) {
              if (_data.hasOwnProperty(property))
                  this[property] = _data[property];
          }
          this.email = _data["email"];
          this.password = _data["password"];
      }
  }

  static fromJS(data: any): RegisterRequest {
      data = typeof data === 'object' ? data : {};
      let result = new RegisterRequest();
      result.init(data);
      return result;
  }

  toJSON(data?: any) {
      data = typeof data === 'object' ? data : {};
      for (var property in this) {
          if (this.hasOwnProperty(property))
              data[property] = this[property];
      }
      data["email"] = this.email;
      data["password"] = this.password;
      return data;
  }
}

export interface IRegisterRequest {
  email?: string;
  password?: string;

  [key: string]: any;
}

export class User implements IUser {
  id?: number;
  createdBy?: number;
  email?: string;
  password?: string;
  isActive?: boolean;
  createdAt?: string;
  modifiedAt?: string;

  [key: string]: any;

  constructor(data?: IUser) {
      if (data) {
          for (var property in data) {
              if (data.hasOwnProperty(property))
                  (<any>this)[property] = (<any>data)[property];
          }
      }
  }

  init(_data?: any) {
      if (_data) {
          for (var property in _data) {
              if (_data.hasOwnProperty(property))
                  this[property] = _data[property];
          }
          this.id = _data["id"];
          this.createdBy = _data["createdBy"];
          this.email = _data["email"];
          this.password = _data["password"];
          this.isActive = _data["isActive"];
          this.createdAt = _data["createdAt"];
          this.modifiedAt = _data["modifiedAt"];
      }
  }

  static fromJS(data: any): User {
      data = typeof data === 'object' ? data : {};
      let result = new User();
      result.init(data);
      return result;
  }

  toJSON(data?: any) {
      data = typeof data === 'object' ? data : {};
      for (var property in this) {
          if (this.hasOwnProperty(property))
              data[property] = this[property];
      }
      data["id"] = this.id;
      data["createdBy"] = this.createdBy;
      data["email"] = this.email;
      data["password"] = this.password;
      data["isActive"] = this.isActive;
      data["createdAt"] = this.createdAt;
      data["modifiedAt"] = this.modifiedAt;
      return data;
  }
}

export interface IUser {
  id?: number;
  createdBy?: number;
  email?: string;
  password?: string;
  isActive?: boolean;
  createdAt?: string;
  modifiedAt?: string;

  [key: string]: any;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any; };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
      super();

      this.message = message;
      this.status = status;
      this.response = response;
      this.headers = headers;
      this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
      return obj.isApiException === true;
  }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
  if (result !== null && result !== undefined)
      throw result;
  else
      throw new ApiException(message, status, response, headers, null);
}
